# Meta
description: mirone's blog.
keywords: hexo,mirone,blog
site_desc: live and let die

# Navigation
navigation:
- name: Home
  slug: home
  url: /
- name: Archives
  slug: archives
  url: /archives
- name: RSS
  slug: rss
  url: /atom.xml
# - name: About
#   slug: about
#   url: http://otakism.org/about
# - name: Works
#   slug: works
#   url: http://otakism.org/works

# Search
search: 
  enable: true
  service: hexo # choose from: google, hexo
  api_key: 
  engine_id: 

# Miscellaneous
google_analytics:
favicon: /favicon.ico
author_url: https://lovin0730.github.io

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/lovin0730
- slug: rss
  url: /atom.xml
- slug: twitter
  url: https://twitter.com/xy610888871
# - slug: facebook
#   url: https://www.facebook.com/mironeXiao
# - slug: email
#   url: mailto:i@artifact.me
# - slug: google
#   url: https://plus.google.com/+ArtChenOtakism/posts
# - slug: linkedin
#   url: # https://www.linkedin.com/in/buzun
# - slug: weibo
#   url: http://weibo.com/otakism/
# - slug: tumblr
#   url: # http://artchen.tumblr.com
# - slug: dribbble
#   url: https://dribbble.com/xy610888871
# - slug: pinterest
#   url: # https://www.pinterest.com/otakism/
# - slug: instagram
#   url: # https://instagram.com/otakism/
# - slug: behance
#   url: # https://www.behance.net/artchen

